# Generated by Django 3.1.7 on 2021-03-28 14:39

from django.db import migrations
import django.db.models.fields.related
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210328_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.fields.related.ForeignKey, to='api.category'),
        ),
    ]
